CREATE TABLE IF NOT EXISTS todos (
  id SERIAL PRIMARY KEY ,
  title VARCHAR(255) NOT NULL,
  todo_description VARCHAR(255),
  completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);